name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
        # No cache option here!

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: VAYU_website/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('VAYU_website/package-lock.json', 'VAYU_website/yarn.lock') }}

      - name: Install dependencies
        run: npm ci
        working-directory: VAYU_website

      - name: Build with Next.js
        run: npx next build
        working-directory: VAYU_website

      - name: Export static site
        run: npx next export
        working-directory: VAYU_website

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: VAYU_website/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
